name: CI
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

# permissions needed for create releases and push to ghcr
permissions:
  contents: write
  packages: write
  pull-requests: read

# define the coverage threshold for the rest of the build
env:
  COVERAGE_THRESHOLD: '80'
  NODE_VERSION: '20'
  OS: ubuntu-latest

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use nodejs environment
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm' 
      - name: Install dependencies
        run: npm ci
      - name: Smoke Tests
        run: |
          npm start &  SERVER_PID=$!
          sleep 5
          $GITHUB_WORKSPACE/scripts/smoke-test.sh
          kill $SERVER_PID || true

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm' 
      - name: Install dependencies
        run: npm ci
      - name: Run tests with coverage
        run: npm run test:coverage -- --coverageReporters="json-summary" --coverageDirectory=coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ env.NODE_VERSION }}
          path: coverage
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Enforce coverage threshold
        env:
          COVERAGE_THRESHOLD: ${{ env.COVERAGE_THRESHOLD || '80' }}
        run: |
          python .github/scripts/get_coverage.py

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Super-Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          IGNORE_GITIGNORED_FILES: true
  
  release_dry_run:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: 
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm' 
      - run: npm ci
      - name: semantic-release (dry-run)
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: npx semantic-release --dry-run
  
  release:
    needs: [lint, test]
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: 
          node-version: ${{ env.NODE_VERSION }} 
          cache: 'npm'
      - run: npm ci
      - run: npm i --save-dev conventional-changelog-conventionalcommits
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  helm-lint:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Setup Helm
        uses: azure/setup-helm@v4
        
      - name: Lint Helm Chart
        run: |
          PROJECT_NAME=$(node -p "require('./package.json').name")
          helm lint "charts/$PROJECT_NAME"

  bump_helm_chart:
    runs-on: ubuntu-latest
    needs: [release, helm-lint]
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Read latest tag → version
        id: ver
        run: |
          set -euo pipefail
          TAG=$(git describe --tags --abbrev=0)
          VER=${TAG#v}
          echo "tag=$TAG"   >> $GITHUB_OUTPUT
          echo "ver=$VER"   >> $GITHUB_OUTPUT
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
      - name: Bump Chart.yaml & values.yaml
        env:
          VER: ${{ steps.ver.outputs.ver }}
        run: |
          PROJECT_NAME=$(node -p "require('./package.json').name")
          CHART_DIR="charts/$PROJECT_NAME"
          yq -i '.version = env(VER)'     "$CHART_DIR/Chart.yaml"
          yq -i '.appVersion = env(VER)'  "$CHART_DIR/Chart.yaml"
          yq -i '.image.tag = env(VER)'   "$CHART_DIR/values.yaml"
      - name: Commit & push (skip CI)
        run: |
          PROJECT_NAME=$(node -p "require('./package.json').name")
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "charts/$PROJECT_NAME/Chart.yaml" "charts/$PROJECT_NAME/values.yaml"
          git commit -m "chore(chart): bump to ${{ steps.ver.outputs.ver }} [skip ci]" || echo "No changes"
          git push

  docker-build-publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU and buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value={{tag}}
            type=sha
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  package_and_push_helm_chart:
    runs-on: ubuntu-latest
    needs: bump_helm_chart  
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Read version
        id: ver
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "ver=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Helm login to GHCR
        run: echo $CR_PAT | helm registry login ghcr.io -u $GITHUB_ACTOR --password-stdin
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Package & Push
        env:
          VER: ${{ steps.ver.outputs.ver }}
        run: |
          PROJECT_NAME=$(node -p "require('./package.json').name")
          CHART_DIR="charts/$PROJECT_NAME"
          REPO_OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f1)
          helm package "$CHART_DIR" --version "$VER" --app-version "$VER"
          helm push "$PROJECT_NAME-$VER.tgz" "oci://ghcr.io/${REPO_OWNER,,}/charts"
      
      




    