name: Internal Registry Leak Guard
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
  pull-requests: read
jobs:
  scan-internal-data:
    name: Scan for internal/unwanted data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run internal data scan
        run: bash .github/scripts/check-internal-data.sh

