name: PR Validation
on:
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  pull-requests: read

jobs:
  ci-core:
    uses: ./.github/workflows/ci-core.yaml
    permissions:
      contents: read
      pull-requests: read
