name: Release
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  NODE_VERSION: '20'
  CHART_DIR: ./charts/it-works-on-my-machine

jobs:
  release-version:
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/npm
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-chart:
    needs: release-version
    uses: ./.github/workflows/helm-build-publish.yaml
    with:
      version: ${{ needs.release-version.outputs.new_release_version }}
    permissions:
      contents: read
      packages: write

  build-publish:
    needs: release-version
    uses: ./.github/workflows/docker-build-publish.yaml
    with:
      version: ${{ needs.release-version.outputs.new_release_version }}
    permissions:
      contents: read
      packages: write

  deploy-and-test:
    needs: [build-publish, release-chart, release-version]
    if: needs.release-version.outputs.new_release_published == 'true'
    uses: ./.github/workflows/deploy.yaml
    with:
      version: ${{ needs.release-version.outputs.new_release_version }}
      environment: staging
    permissions:
      contents: read
      packages: read

